### ISSUE TITLE
Output now contains "," on larger outputs.

### ISSUE THREAD

**Issue by joandrsn** [IonicaBizau/powershell#14]
Still new to open source projects.
With 4df80971f9978fac043a5d925bdda56035f9c473 commit the output was buffered in an array and on process end, the output was sent to potential subscribers.
I believe the usage of chunks and arrays alters the output from PowerShell.
According to [mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join), `join()` on an array adds `,` between the chunks.

I understand how this adds support for larger output but is this valued higher than correct output?

Again still new to javascript, so is there a way where both request for correct output and the request for a larger output can be satisfied?

**Comment by IonicaBizau** [comment]
> Still new to open source projects.

Welcome! 😄 

> I believe the usage of chunks and arrays alters the output from PowerShell.

You may be correct. If the chunk is an array, it will be pushed, instead of concatenated.

```
> [["foo", "bar"], "baz"].join("")
'foo,barbaz'
```

@obsidience In what cases are we going to receive chunks as arrays?

@joandrsn The fix should be quite simple: we check if the `chunk` is an array and if so, we **`chunks.push.apply(chunks, chunk)`** instead of `chunks.push(chunk)`—this will concatenate the arrays.

Would you like to contribute and fix this? You can simply [click the "edit" (✏️) button](https://github.com/IonicaBizau/powershell/edit/master/lib/index.js) and edit that piece of code, and then create a *Pull request*. 🚀

**Comment by joandrsn** [comment]
Upon further investigation I believe that `chuck` is always a string.

Something as simple as this illustrates the problem for me (If you can't reproduce, then try with a higher number instead of 10):
```const PowerShell = require("powershell");

let ps = new PowerShell("1..10");

ps.on("output", data => {
    console.log(data);
});
```

The output:
```PS C:\temp\test> node .
1
,2
,3
4
5
,6
,7
,8
,9
,10
```


If I change `chunks` to a string and instead do `chunks += chunk;` and output only `chunks` I get the following output:
```
PS C:\temp\test> node .
1
2
3
4
5
6
7
8
9
10
```

But I'm not sure if this method allows the larger output that @obsidience mentioned in his commit.

**Comment by IonicaBizau** [comment]
Can you simply `console.log(chunk)`, [here](https://github.com/IonicaBizau/powershell/blob/master/lib/index.js#L62)? I do believe the `chunk` is sometimes an array.


Change that line into:

```js
_proc.stdout.on("data", chunk => { console.log(chunk); chunks.push(chunk); });
```

**Comment by joandrsn** [comment]
Output with the line changes @IonicaBizau 
```
PS C:\temp\test> node .
1

2
3
4
5
6
7
8
9
10

1
,2
3
4
5
6
7
8
9
10
```

It's a bit hard to see whats going on. 
But I changed it to ``console.log(`"${chunk}"`);`` and this was the output:


```
PS C:\temp\test> node .
"1
"
"2
3
4
5
6
7
8
9
10
"
1
,2
3
4
5
6
7
8
9
10
```

**Comment by IonicaBizau** [comment]
Can you also do `console.log(typeof chunk, chunk.constructor.name, chunk)`?

**Comment by IonicaBizau** [comment]
Or even better, do `console.log(chunks)`, [here](https://github.com/IonicaBizau/powershell/blob/master/lib/index.js#L69).

**Comment by joandrsn** [comment]
Output from `console.log(typeof chunk, chunk.constructor.name, chunk)`: 
```
PS C:\temp\test> node .
string String 1

string String 2
3
4
5
6
7
8
9
10

1
,2
3
4
5
6
7
8
9
10

```

Output from `console.log(chunks)` on process close:

```
PS C:\temp\test> node .
[ '1\r\n',
  '2\r\n',
  '3\r\n4\r\n',
  '5\r\n',
  '6\r\n',
  '7\r\n',
  '8\r\n',
  '9\r\n',
  '10\r\n' ]
```

**Comment by IonicaBizau** [comment]
> According to mozilla documentation, `join()` on an array adds , between the chunks.
@joandrsn Oh, you're right: we need `join("")` instead. I totally missed we used `join()` instead of `join("")`.

But still, we need to do the concatenation thingy, just in case we get arrays. I'm not sure what are the cases when the `chunk` is an array.

Good catch!
