### ISSUE TITLE
No output at all in version 2.1.7

### ISSUE THREAD

**Issue by joandrsn** [IonicaBizau/powershell#17]
Hope you haven't grown tired of me yet 😁 

Using the [wiki example](https://github.com/IonicaBizau/powershell#clipboard-example) in version 2.1.7 results in no output. Events seem to not emit properly or example is now different.
Version 2.1.6 printed the output `powershell is awesome`.

**Comment by IonicaBizau** [comment]
Whoups! :boom: 

Does your example still work?

```js
const PowerShell = require("powershell");

let ps = new PowerShell("1..10");

ps.on("output", data => {
    console.log(data);
});
```

**Comment by IonicaBizau** [comment]
Oh, I know why!
