### ISSUE TITLE
Output only writes on process close

### ISSUE THREAD

**Issue by joandrsn** [IonicaBizau/powershell#19]
I have a long running PowerShell script, taking sometimes up towards 2 minutes.
I liked when the output was emitted when it happened as it allowed me to see how far along the processing of the PowerShell script was.

My suggestion is to make an option variable called `instantoutput` which when set to `true` makes the PowerShell script output as soon as the output is written.

Is this acceptable?

**Comment by IonicaBizau** [comment]
We can expose the `_proc` variable in `this` so then you can simply `pipe` the stream to the `process.stdout`.

An option like that would be handy too!

**Comment by joandrsn** [comment]
That would be great! That way, users of this project can chose how/when they want the output!
Is it as simple as adding a line after [L77](https://github.com/IonicaBizau/powershell/blob/master/lib/index.js#L77) with this:
`this.proc = _proc;`

Or did you have something different in mind?

**Comment by IonicaBizau** [comment]
Exactly. That's right. 😊
