### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dgrfdsgn** [IonicaBizau/powershell#32]
https://cdn.rawgit.com/rannn505/node-powershell/236b6c3a/docs/docs.html seems not working from here..?

**Comment by dgrfdsgn** [comment]
Mixed Content: The page at 'https://cdn.rawgit.com/rannn505/node-powershell/236b6c3a/docs/docs.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
flatdoc.js:521 Uncaught ReferenceError: jQuery is not defined
    at flatdoc.js:521
script.js:74 Uncaught ReferenceError: jQuery is not defined
    at script.js:74
docs.html:26 Uncaught ReferenceError: Flatdoc is not defined
    at docs.html:26
docs.html:47 Mixed Content: The page at 'https://cdn.rawgit.com/rannn505/node-powershell/236b6c3a/docs/docs.html' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=rannn505&repo=node-powershell&type=watch&count=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by IonicaBizau** [comment]
But that's another project.
