### ISSUE TITLE
Possible to use Powershell attached with the application?

### ISSUE THREAD

**Issue by ALIENQuake** [IonicaBizau/powershell#33]
Any clue which lines I need to edit in order to use Powershell attached with the application?

**Comment by ALIENQuake** [comment]
@IonicaBizau Hey, I would really be grateful if you could quick look at the code and reply even if it is currently impossible.

**Comment by IonicaBizau** [comment]
What do you mean by _attached with the application_?

**Comment by ALIENQuake** [comment]
Node-powershell will always try to "execute" powershell.exe/pwsh.exe which is installed on system. I need a way for node-powershell to execute powershell.exe/pwsh.exe from node-powershell/electron root app directory. So for eg. application distribution folder will have:

```
MyApp\MyApp.exe
MyApp\`<dll and other files`>
MyApp\powershell\`<dll and other files of powershell portable archive`>
```
so when I execute powershell commands from node-powershell/electron app, it will execute one of above. I'm aware about the fact that the 'powershell' folder must be provided after build.

**Comment by IonicaBizau** [comment]
We should make this configurable: https://github.com/IonicaBizau/powershell/blob/master/lib/index.js#L32

**Comment by ALIENQuake** [comment]
@IonicaBizau Could you simply add one if...:
```
if <AppExecutableMainDirectory>\Powershell exist then
opt.PSCore = <AppExecutableMainDirectory>\Powershell\pwsh${isWin() ? ".exe" : ""}
```
would this be enough for first implementation?
