### ISSUE TITLE
Allow NoProfile and different Execution Policy

### ISSUE THREAD

**Issue by joandrsn** [IonicaBizau/powershell#7]
When powershell runs, it loads the profile.
Depending on my profile, this might take some time.
This could be solved by using `-NoProfile` when launching PowerShell.

Also sometimes I would like to use another execution policy.
This could be solved by using `-ExecutionPolicy` when launching PowerShell.

Maybe consider adding parameters to the `opt`-object.

**Comment by IonicaBizau** [comment]
That would be cool! Contributions are welcome!

**Comment by IonicaBizau** [comment]
Released in the latest version. 🚀
